### ISSUE TITLE
ServerDataSource: Setting filters sends new network request when doEmit=true 

### ISSUE THREAD

**Issue by SZOKOZ** [dj-fiorex/angular2-smart-table#105]
```
const source = new ServerDataSource(this.http,
      {
        endPoint: `${this.apiUrl}/${uri}`,
        dataKey: '',
        pagerPageKey: 'pageNumber',
        pagerLimitKey: 'pageSize',
        filterFieldKey: 'filterBy#field#',
        sortFieldKey: 'sortBy',
        sortDirKey: 'orderBy',
      });
    source.setFilter([
      {
        field: 'type',
        search: 'engine',
      },
    ]); // Results in a http get request
    source.setPaging(1, 1); // Results in a http get request
    
    // Actual intentional attempt to retrieve data.
    source.getElements().then(response => console.log(response));
```

Setting the filter calls the parent set filter which emits a filter event calling [emitOnChanged](https://github.com/dj-fiorex/angular2-smart-table/blob/master/projects/angular2-smart-table/src/lib/lib/data-source/data-source.ts#L167) leading to a http call with the currently set filter. Setting paging has the same issue.

In the docs the doEmit flag is used to determine whether or not the table is refreshed and theoretically helpful for detecting changes but what it actually does is grossly different.

**Comment by uap-universe** [comment]
I am not sure if I understand the issue correctly.

Changing the pagination or the filter _must_ result in a http request, because the items of the current page might change.

If the observation is, that an _additional_ http request with the _old_ and _outdated_ filter or pagination is sent, then this is obviously a bug.

Can you please clarify?

**Comment by uap-universe** [comment]
It looks like the `ServerDataSource` needs to remember the last query parameters s.t. subsequent calls to

* getAll()
* getElements()
* getFilteredAndSorted()

can return the last result without issuing a new request. On the other hand, there needs to be a way to invalidate this "cache", because otherwise you would not get fresh data from the server.

I will override the `refresh()` method for this. This way you get new data from the server

* every time the query changes (changing the page or the filter)
* on explicit calls of `refresh()`

In my opinion the `ServerDataSource` is a bit broken anyway, because it inherits from `LocalDataSource` but has completely different semantics. For example I don't know what `prepend` or `empty` should mean in the context of a `ServerDataSource`....
