### ISSUE TITLE
Creation of a loading callback for remote

### ISSUE THREAD

**Issue by abrahampe** [dj-fiorex/angular2-smart-table#122]
While waiting for remote data, the table shows NO DATA message, is possible to show uma image/animation?

**Comment by uap-universe** [comment]
You can implement a separate UI element that is displayed when the page is loaded and hidden when the data source emits the loaded event.

You can also change the `noDataMessage` in the settings. 

I don't know if changing the `noDataMessage` at runtime has any effect, because it is only updated onChanges but I don't know if (or when) change detection fires for the tbody component.

So maybe first try to set `noDataMessage` to something like "Data is loading" and once you know that there is no data from the server, you can try updating the settings with a `noDataMessage` that reads "No data found."

But please note, that the original developers never had changing the settings at runtime in mind, so if it works, it only works accidentally.

**Comment by abrahampe** [comment]
Thanks a lot! I will set the noDataMessage to false, and try to show my own message as clear as possible! If I get some workaround I write here!
