### ISSUE TITLE
Problem in migration to angular2-smart-table: List filters doesn't work.

### ISSUE THREAD

**Issue by pj-alvarado10** [dj-fiorex/angular2-smart-table#135]
Hi! I migrated in my angular 16 app to angular2-smart-table. I must upgrade rjx version too. All things works perfectly, except the filters. I have some filters of list type. 

I have a list filter of true/false (exists undefined values) but it is not a checkbox filter, because is of this way:

 ```
   filter: {
          type: 'list',
          config: {
            selectText: 'Select..',
            list: [
              { value: true, title: "Rural" },
              { value: false, title: "Urban" }
            ],
          },
        },
```

First problem: The value is only string, then I must put the true and false inside quotation marks: 'true' and 'false'.
Second problem: The filter doesn't work but it doesn't have errors.

Other filter is with numbers values: 

```
  filter: {
          type: 'list',
          config: {
            selectText: 'Seleccione...',
            list: [
              { value: 0, title: "Flexibble" },
              { value: 1, title: "Fixed" }
            ],
          },
        },
```

First problem: The value is only string, then I must put the 0 and 1 inside quotation marks: '0' and '1'.
Second problem: The filter doesn't work but it doesn't have errors.

And I have other filter with the value string but different title and value, and the filter doesn't work neither and it doesn't have errors.

I didn't find a similar case in [the documentation](https://dj-fiorex.github.io/angular2-smart-table/documentation).

What thing must I change to the list filter works?

Thank you!!

**Comment by uap-universe** [comment]
The smart table filter has always been a "string includes" filter and only worked for numbers by accident.

That means, a filter for value "1" would also find entries with value "10", "11", "21", "315", and so on.

That is why I introduced the `strict` property in smart-table version 2.8.0.

What it does, is that it changes the default filter function from `v.includes(s)` to `v === s`. But that obviously only works when the _types_ of `v` and `s` also match. So in 2.8.0 and 2.9.0 it worked perfectly, because the type of `s` was quite arbitrary, but in version 3.0.0 it is forced to be `string`.

I have opened #136 to address this issue. In the meantime, the following workaround works:

```typescript
  filter: {
         type: 'list',
         config: {
           strict: false,  // disable overriding the filter function
           selectText: 'Select..',
           list: [
              // your select options
           ],
         },
         filterFunction: (v,s) => v.toString() === s
       },
```

For numbers - bot not for booleans, this also works (but I don't think it is super reliable):

```typescript
         filterFunction: (v,s) => v == s // non-type-checking comparison
```

If your column contains null or undefined values, you need to do this:

```typescript
         filterFunction: (v,s) => (v?.toString() ?? '_magic_placeholder_for_null_') === s
```

**Comment by pj-alvarado10** [comment]
Thank you so much! Your answer works perfectly!

The filter function must be outside the filter section.
```
  filter: {
              // your filter settings here
       }
  filterFunction: (v,s) => v.toString() === s
```

The filter function to null or undefined works magically! Thank you!! so much!
