### ISSUE TITLE
Passing smart table filtering and ordering to URL

### ISSUE THREAD

**Issue by AnejVovcak** [dj-fiorex/angular2-smart-table#143]
Hello! Do any of you know how I can pass the smart table filtering and ordering to URL? I need to persist the user’s smart table configuration for when they are moving to different pages in the application. Is this feature implemented by any chance? If not, I would much appreciate it.

Thank you for maintaining this library, everyone!

**Comment by uap-universe** [comment]
You can extract the information with the methods of the data source.

```
  getSort(): Array<ISortConfig>
  getFilter(): Array<IFilterConfig>
  getPaging(): IPagingConfig
```

You can, for example, invoke those methods in the `ngDestroy` hook of your page and store them somewhere. I think what you really want is to store the info in the local storage and avoid polluting your URL. Unless your intention is to make this information available for sharing, of course. In that case I recommend, to base64-encode the information first, before constructing query parameters.

**Comment by AnejVovcak** [comment]
Thank you for your response! This is a good approach. The only problem seems to be the paging. It gets overwritten somehow. I am using ServerDataSource. At first, the correct page is passed to the object, but it then gets overwritten. Do you have any idea why? I’ve also looked into DataSource and LocaleDataSource and didn’t find anything extraordinary. Mind you that I am using a slightly adapted ServerDataSource, since my REST API filtering is using offset and limit instead of page and perPage. Thank you for effort!

```javascript
protected addPagerRequestParams(httpParams: HttpParams): HttpParams {
    // MODIFIED pagerPageKey now works as an offset
    httpParams = httpParams.set(this.conf.pagerPageKey, (this.pagingConf.page - 1) * this.pagingConf.perPage);
    httpParams = httpParams.set(this.conf.pagerLimitKey, this.pagingConf.perPage);
    return httpParams;
  }
```

**Comment by uap-universe** [comment]
Indeed, when the table grid is built and the data source is prepared, the selected page is recalculated based on the provided settings. 

https://github.com/dj-fiorex/angular2-smart-table/blob/b385ac3759dee048b94175a5be3afd10ee32af28/projects/angular2-smart-table/src/lib/lib/grid.ts#L260-L269

The `getPageToSelect()` method uses, among other things, this method to determine which page to select.

https://github.com/dj-fiorex/angular2-smart-table/blob/b385ac3759dee048b94175a5be3afd10ee32af28/projects/angular2-smart-table/src/lib/lib/grid.ts#L304-L311

I cannot figure out a clean solution at the moment. But maybe a short term workaround for you is to defer a manual call to your DataSource's `setPaging` method to the end of the event queue (or maybe plus 100ms, if that does not work) and enforce the paging settings loaded from the query parameters, after loading the table.

But be aware that this might not always be unproblematic, because information on the server might have changed and the page might not be valid anymore, so some out of bounds handling would still be necessary.

**Comment by uap-universe** [comment]
I assume the question is answered and did not raise any follow-up questions. Please re-open ticket, otherwise.
