### ISSUE TITLE
Cannot set type of column because  IColumnType detected undefined  Type 'string' is not assignable to type 'IColumnType | undefined'

### ISSUE THREAD

**Issue by marvelzmoon** [dj-fiorex/angular2-smart-table#155]
Hi, 

i hav datatable that need using html type column. On version 3.1.1 using angular 16 istill use html column type. but when i upgrade using version 3.2.0 i got issue with  IColumnType.
 this my table settings
```ts
 tableSettings =  {
    columns: {
      status: {
        title: '',
        class:'column align-center',
        type:'html'
      },
      id:{
        title: 'ID',
        class:'column align-center'
      },
      name:{
        title: 'Name',
        class:'column align-center'
      }
    },
    editable:false,
    pager:{
      perPage:10
    },
    actions:{
      add:false,
      edit:false,
      delete:false,
    }
 }
```

and this what i get 

```js
Types of property 'columns' are incompatible.
    Type '{ status: { title: string; class: string; type: string; }; id: { title: string; class: string; }; name: { title: string; class: string; }; }' is not assignable to type 'IColumns'.
      Property 'status' is incompatible with index signature.
        Type '{ title: string; class: string; type: string; }' is not assignable to type 'IColumn'.
          Types of property 'type' are incompatible.
            Type 'string' is not assignable to type 'IColumnType | undefined'. [plugin angular-compiler]
```

how i suppose deal with it. Any change that type cannot using string anymore? 

ANGULAR 17.0

**Comment by uap-universe** [comment]
I think the problem is that you don't specify the type annotation explicitly.

The typescript compiler is rather stupid. It does not recognize that the `string` you specify is actually compatible to `IColumnType`.

From the point of view of the compiler, your `tableSettings` variable does not even have the type `Settings`. I _think_ it should be sufficient to explicitly annotate the type (`tableSettings: Settings`). 

Please try this first, if it doesn't work, we'll find a solution.

**Comment by marvelzmoon** [comment]
Sorry too late for me to reply.
thank you so much for your response. it's worked.
I think after update to angular version 17 they made strict on annotation explicitly. For me who doesn't give too much care on annotation data type need change habit.
