### ISSUE TITLE
Change filterFunction parameter from cellValue to Cell

### ISSUE THREAD

**Issue by marcosdenoni** [dj-fiorex/angular2-smart-table#158]
Necessity: in the old version, the filterFunction function receive the cell that was being filtered as parameter, making it possible to execute more complex filters. As of version 3.1.0 this has been removed.

It would be interesting in this function to pass the cell instead of the value.

from:
export type ColumnFilterFunction = (value: any, searchString: string) => boolean;

to:
export type ColumnFilterFunction = (cell: Cell, searchString: string) => boolean;

or add a new parameter to get the cell:
export type ColumnFilterFunction = (value: any, searchString: string, cell: Cell) => boolean;

**Comment by marcosdenoni** [comment]
looking for change I found it in #117 . As an additional point, the cell variable contains the current value of the cell, the row datasource and access to other information for creating a composite filter

**Comment by uap-universe** [comment]
One of the reasons why it was removed is, because it opened the door wide open for misuse scenarios in which the filter is not working properly.

Composite filters are one of those misuse cases.

The filterFunction is for implementing the column filter, and actually the column filter only.

For the column filter you don't need anything else than the cell value. If you are using any other information, you are already implementing a different kind of filter.

The "correct" way of implementing a composite filter would be to add this as a function to your extension of the DataSource class.

For example if you want a global filter that filters every *row* that contains some keyword in *any* of it's columns, you would implement this mechanism directly in the data source and only give the data to the table that matches the global filter. This data could then (afterwards) be filtered by the column filters of the table.

Another example would be combining the filters via *logical or* instead of *logical and*. There were ideas in previous versions of the smart table, but those failed miserably and had various sorts of bugs.

**Comment by marcosdenoni** [comment]
It makes sense.
 One question about valuePrepareFunction: does it prepare the raw value? I mean, if a number is returned, the sorting will continue to work?

**Comment by uap-universe** [comment]
The default compare function is implemented in the [local.sorter.ts](https://github.com/dj-fiorex/angular2-smart-table/blob/master/projects/angular2-smart-table/src/lib/lib/data-source/local/local.sorter.ts).

It tries to be as smart as possible to detect if your column consists of numerical values and then sort them accordingly. 

On the other hand, the purpose of the `valuePrepareFunction` is to convert any value to a string value. It shall not return a value of any other type than string.

The reason is, that the value returned by the `valuePrepareFunction` is used in the HTML to present the table. And that MUST be a string. For presentation this is not as important as for editing, because when you bind a value to an HTML input, it MUST be a string.

Not so many developers know this about Angular, and so the original developers of the smart table did not know.

The effect was, that when you bind a _number_ to an inline editor of the smart table, and then confirm the new value, it will be automatically converted to a string. 

Suppose you have a row with three number columns. When you start editing them with the inline editor, but only change one of them, the changed value will have type string and the other will still have type number, causing the type confusion from hell (see also #115 ).

This is the reason why the `valuePrepareFunction` shall translate the value of the data object to a presentable string for the use in HTML, and, more recently, the `valueStoreFunction` is supposed to do the exact opposite and translate the _string_ entered by the user back to the value of the correct type in the data model.

**Comment by Pirer24** [comment]
> One of the reasons why it was removed is, because it opened the door wide open for misuse scenarios in which the filter is not working properly.
> 
> Composite filters are one of those misuse cases.
> 
> The filterFunction is for implementing the column filter, and actually the column filter only.
> 
> For the column filter you don't need anything else than the cell value. If you are using any other information, you are already implementing a different kind of filter.
> 
> The "correct" way of implementing a composite filter would be to add this as a function to your extension of the DataSource class.
> 
> For example if you want a global filter that filters every _row_ that contains some keyword in _any_ of it's columns, you would implement this mechanism directly in the data source and only give the data to the table that matches the global filter. This data could then (afterwards) be filtered by the column filters of the table.
> 
> Another example would be combining the filters via _logical or_ instead of _logical and_. There were ideas in previous versions of the smart table, but those failed miserably and had various sorts of bugs.

Okay, but what about a situation when we have an object within an object? Now, we used `valuePrepareFunction` to prepare and select a value from an object. So, if we want filters for this column, we have to also set `filterFunction`, because SmartTable doesn't know that we used a combined value from an object within an object.
For now, in the newest version, it cannot be done (no data about row/cell in `filterFunction`), but maybe I'm wrong, and there is a new way to set filters. 😋

**Comment by uap-universe** [comment]
I don't know if I really get what you are doing. But it sounds like you are not filtering on the value displayed in the cell and instead of the underlying data? That would be misuse of the column filter.

The intention of the column filter is that you enter a text and get only the rows where the *cell text* contains what you have entered in the filter.

For example, let's say your object contains data about a book with title and ISBN and your valuePrepareFunction only returns the title. But when you use the filter, you want to also match the ISBN. I can understand the idea, but that is not what the column filter is supposed to be doing. It shall only filter what you can actually see in the cell.

**Comment by marcosdenoni** [comment]
> The effect was, that when you bind a _number_ to an inline editor of the smart table, and then confirm the new value, it will be automatically converted to a string.
> 

Now thats make sense, 

I recently re-implemented it making the necessary corrections and now it is in agreement, however the valueStoreFunction function should help with some workarounds carried out to correct the text conversion behavior!

**Comment by marcosdenoni** [comment]
@uap-universe, I arrived in a scenario where the value is a date '2024-05-22' however the valuePrepareFunction is used to prepare the value for '22/05/2024', when the filter is performed the raw value is passed (2024-05-22) and not the one prepared by valuePrepareFunction

Wouldn't it be correct to use the value rendered in the filter function?

**Comment by uap-universe** [comment]
In a matter of speaking, yes. You should use the "value" that is displayed to the user for filtering. But the input for the filter function is not necessarily exactly the string that is prepared for the HTML of the cell.

For example you could use 'html' instead of 'text' in your column and your `valuePrepareFunction` adds some fancy formatting, for example making some part of the text appear bold or underlined.

You would not want those HTML tags to match any of your filter queries.

A good solution in your case would be to define the function that converts your raw value to a string and call that function from both the valuePrepareFunction as well as the filterFunction.

In the scenario where you want to add some HTML formatting, you would post-process the value from your convert-function in the valuePrepareFunction to add the formatting, but don't invoke it in the filterFunction.

**Comment by marcosdenoni** [comment]
good thats solve the problem!
