### ISSUE TITLE
[Feature Request] Ability to pass rows type as an TS Interface/Type. 

### ISSUE THREAD

**Issue by tawfiek** [dj-fiorex/angular2-smart-table#28]
Make table configuration accepting a typescript interface to strongly typed rows data,
This might add some flexibility and confidence while loading data to the table, and also make it easier to manipulate data in the tables.

**Comment by uap-universe** [comment]
In my current project we have a huge typed abstraction for the smart table settings. But for the original settings, though. 

I am too reluctant to provide this as a pull request here, because it is very specific and tends to cover only the settings we actually use in our project. Also, we implemented it as a layer on top of the (previously) untyped settings and after migrating to this fork, we just changed that layer to be compatible with this fork.

In our settings functions like `valuePrepareFunction` are statically typed as well as the column properties. So let's say you have an object

```
class Foo {
   bar: number
   baz: boolean
}
```

You would create smart table settings like this

```
settings = {
    // ...
   bar: {
       // bar column settings
   },
   baz: {
       // baz column settings
   }
}
```

Our implementation checks that you spell the property names correctly, and also checks that the type in the column settings is compatible. We also have helper functions `makeTextColumn`, `makeNumberColumn`, `makeEnumColumn` etc. that spare you the verbose and repetitive definition of column settings.

It is *possible* that I gradually formulate pull requests for these features some time in the future. But again, they are very specific and very custom so maybe it would be wise to just provide them as an add-on layer (as it is right now) because I do not want to force everybody to think they way we did in our project.

**Comment by tawfiek** [comment]
It would be nice of course, if we had a look at your abstraction, Maybe we can came up together with something more generic starting with your team's abstraction.

In my codebase we have tons of repetitive tables settings in various components, Hopefully I can contain this amount of code by migrating to this fork soon.

**Comment by dj-fiorex** [comment]
Please @uap-universe try to share as much as you can, because i think that your solution is good to eliminate an all kind of problems working with the table! Thanks

**Comment by uap-universe** [comment]
relates to #65

**Comment by uap-universe** [comment]
I am using a very old management trick and close this ticket in favor of continuing the discussion in #127. This way it looks like we are not sleeping on the job 😆😆
