### ISSUE TITLE
Get page number on click event on pagination link

### ISSUE THREAD

**Issue by kumarmanishc** [dj-fiorex/angular2-smart-table#61]
First I thank you, 
For such great initiative to create fork of ng2-smart-table.

### Motivation
 I'm trying to get page number on click of a page number of pagination links.

### feature request
Can we add a custom event so on click of pagination, we can get page number for further processing.

**Usability** : 
For some scenario  if we need page number to prepare data for next page with page number
For example if user is on page 1 then app need to prepare data for page 2 and page 3, ...

This will be useful if we can add support for that.

**Comment by FawadNL** [comment]
This is a great idea. This is a **must** feature for our Angular app that uses pagination in DB.

**Comment by uap-universe** [comment]
There is already an implementation of the data source which is called `ServerDataSource`. I have never used that but I would expect that this data source also reacts on page changes. However, I don't think that this immediately solves your problem when you are already using a custom implementation for retrieving the data from the server.

Fortunately, there are already two events that are emitted when something is changed regarding the pagination. The `paging` event is emitted when the paging configuration changes (including the number of items per page). The `page` event is emitted, when the page changes.

You can try the following (please report back if it works for you):

```typescript
        this.dataSource.onChanged().subscribe(event => {
            if (event.action === 'page' || event.action === 'paging') {
                const page = this.source.getPaging().page;
                // your code goes here
```

**Comment by uap-universe** [comment]
@kumarmanishc I will look into it. 

The bad thing is, that the data source events are not [documented](https://dj-fiorex.github.io/angular2-smart-table/documentation). So I do not know the intentions of the original developers.

On the other hand, this might also be a good thing, because we might be able to change that (carefully).

I think it is reasonable to expect that the `page` event is fired, when the page is changed (either programmatically or via the pagination links). 

There are several things I should do for the next release:

1. Document all data source events (needs a little reverse engineering and "interpretation", but should be possible)
2. Document the effects those events already have (will be a bit harder to find all of them)
3. Let the pagination link interactions fire the page events (i.e. find out why that doesn't happen already and then make it happen)
4. Introduce a proper type for the event object
5. Introduce a proper type for the pager object
6. Maybe add the current pager settings to the event payload s.t. you don't need to extract it from the data source when you react on the event

Would that be a solution you can work with?

**Comment by kumarmanishc** [comment]
> Hello @uap-universe This is PR is I already created for this issues #63 
> 
> However I wasn't able to test it.
> I followed step bellow.
> I created build with `npm run build:lib` and then copied _`dist/angular2-smart-table`_ folder to the node_modules of my project.

None of my changes are taking effects even the console logs.

**Can you please guide how can I test this project locally after changes ? 
So I might fix this issue or we can go with custom event as of #63 after testing**

**Comment by uap-universe** [comment]
You do not copy the `angular2-smart-table` by yourself into the `node_modules` folder. Instead you let npm do the job.

Copy `dist/angular2-smart-table` into some folder in your project, let's say `lib/angular2-smart-table`.

Then in your package.json you can change the entry from `"angular2-smart-table": "^2.3.1"` to `"angular2-smart-table": "file:lib/angular2-smart-table"` and then run `npm install` (remove any previous installation of angular2-smart-table before you do that).

Regarding your PR, I cannot approve that. It's more like a hack than a solution. 

The `paginate` function calls `setPage()` here:

https://github.com/dj-fiorex/angular2-smart-table/blob/2de363b5a1a5735369f4480717b859d34a176ce6/projects/angular2-smart-table/src/lib/components/pager/pager.component.ts#L120

The second argument is omitted, but for a `LocalDataSource` it is true. Therefore, the `page` event *should* be emitted. It remains to analyze why you do not receive that event in your application.

I tried the technique described above with one of the demo applications in this project. I added the following lines to the constructor in `basic-example-source.component.ts`:

```typescript
    this.source.onChanged().subscribe((event) => {
      console.log(event);
    });
```

And I get the following event object when changing the page via the pagination:
```json
{
  "action": "page",
  "elements": [
    {
      "id": 11,
      "name": "Nicholas DuBuque",
      "username": "Nicholas.Stanton",
      "email": "Rey.Padberg@rosamond.biz"
    }
  ],
  "paging": {
    "page": 2,
    "perPage": 10
  },
  "filter": {
    "filters": [],
    "andOperator": true
  },
  "sort": []
}
```

So to me it looks like there is anything you would need to react on a pagination event. So I guess it's a bug in your application if that does not work for you.

Is it possible that you overwrite your data source after registering the event handler? Like

```typescript
public datastore: LocalDataSource = new LocalDataSource();

this.datastore.onChanged().subscribe((event) => {
      console.log(event);
    });

// later on ....

this.datastore = // something new
```

**Comment by kumarmanishc** [comment]
@uap-universe For the page change event.
I can see the events for refresh and load
`Event :  
Object { action: "refresh", elements: [], paging: {…}, filter: {…}, sort: [] }
`
When I change page getting following in log but not data.

`WARNING: sanitizing HTML stripped some content, see https://g.co/ng/security#xss 30 core.mjs:5854`

`const datastore : LocalDataSource = new LocalDataSource();` _// Initializing data store._
`this.datastore.load(response.body);` _// loading data to the store._
_// Detect page change event._
`this.datastore.onChanged().subscribe((event) => {
      console.log('Event : ', event);
 })`

Is this something with settings ?

    <angular2-smart-table [settings]="settings" [source]="datastore" (custom)="updateOrderStatus($event)"
      (userRowSelect)="showSalesOrderDetails($event)" (pageSelect)="pageSelect($event)">
    </angular2-smart-table>

```
public settings: Settings = {
    resizable: true,
    columns: {
      id: {
        title: 'Order ID',
        type: IColumnType.Html,
        valuePrepareFunction: (id) => {
          return `<div class="text-color smart-tbl-order-id">#${id}<div>`;
        },
      },
    actions: {
      custom: [
        {
          name: 'create-package',
          title: `<i class="far fa-file-alt" title="View Record"></i>`,
        },
        {
          name: 'update-package',
          title: `<div class="custom-button">Update Status<div>`,
        },
      ],
      add: false,
      edit: false,
      delete: false,
      position: 'right',
    },
    pager: {
      page: 1,
      display: true,
      perPage: 10,
    },
  };
```

**Comment by uap-universe** [comment]
@kumarmanishc it is hard to analyze what's wrong in your setting.

Since you are using a local build of the smart table, you have access to the sources from within your project. So you might be able to set breakpoints here

https://github.com/dj-fiorex/angular2-smart-table/blob/2de363b5a1a5735369f4480717b859d34a176ce6/projects/angular2-smart-table/src/lib/lib/data-source/local/local.data-source.ts#L216

and here

https://github.com/dj-fiorex/angular2-smart-table/blob/2de363b5a1a5735369f4480717b859d34a176ce6/projects/angular2-smart-table/src/lib/lib/data-source/data-source.ts#L106

The first breakpoint shall verify that the specialized function is called and the default value for the `doEmit` parameter is used.

The second breakpoint shall verify that the branch where the event is emitted is actually taken.

If no breakpoint hits whatsover, you might need an additional breakpoint here

https://github.com/dj-fiorex/angular2-smart-table/blob/2de363b5a1a5735369f4480717b859d34a176ce6/projects/angular2-smart-table/src/lib/components/pager/pager.component.ts#L120

to verify, that the function is actually called.

I'm sorry that most of the debugging work lies at your site now, but since I cannot reproduce the behavior (neither in a sample application, nor in my current production application, I always get the page event), I cannot really help.

**Comment by kumarmanishc** [comment]
Thanks @uap-universe This helps to fix the issue.
page navigation is working absolutely fine.
We can close this ticket
