### ISSUE TITLE
Add table-layout: fixed

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#68]
Currently the smart table does not really respect column width settings. You decide that the column shall have width 8rem for example but the true width is not 8rem but some weird mixture of what you "suggested" for the column width and what the table thinks is best.

Another problem is that the sum of column widths (not the widths you have chosen, but the widths the table thinks are best) may exceed the total width of the table. And that results in the table having more actual width than it should have.

As a possible fix we might add `table-layout: fixed` to the style of the `table` element. 

If I understand correctly, the intention of the original authors was to control the column widths via the widths of the header cells anyway. So a fixed table-layout would be the natural choice here.

**Comment by uap-universe** [comment]
@hexdecimal16 @tawfiek  what do you think? Would this change break something in your applications?

**Comment by tawfiek** [comment]
I would say, that will be fine for me.

But let's dive deeper into the use cases.

I think we need some more complex configuration options to tell the table how to behave on different view scales, that will make the table more responsive.

Like give the columns a max and minimum width, and set an optional column to automatically disappear in smaller screens.
Also adding an optional ability to horizontal scroll if all the columns are required or a fixed width are passed to some column and the view width doesn't fit.


As conclusion, I think making the table more flexible and configurable, will be more realistic way to head, rather than enforce a fixed layout and enforce the table to respect some width should be passed by the user, just let's think about that twice.

**Comment by uap-universe** [comment]
We stick with option (1) for the time being, because `table-layout: fixed` would also apparently break the resize column and expand row feature.
